"""removing uncessary claim account

Revision ID: 007efb059813
Revises: 6b39b61481f2
Create Date: 2026-09-29 21:45:43.084406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '007efb059813'
down_revision: Union[str, Sequence[str], None] = '6b39b61481f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'claim_jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('claim_jti', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
