"""new ERD for maps/stores

Revision ID: 020ceb7e35cc
Revises: 054add72d2cd
Create Date: 2026-06-16 18:34:47.183002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020ceb7e35cc'
down_revision: Union[str, Sequence[str], None] = '054add72d2cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('price_range', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Enum('INEXPENSIVE', 'MODERATE', 'EXPENSIVE', name='pricelevel'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price_notes', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_map_id'), 'stores', ['map_id'], unique=False)
    op.add_column('maps', sa.Column('region', sa.String(), nullable=True))
    op.add_column('maps', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('maps', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('maps', 'google_embed_url')
    op.create_unique_constraint('_user_map_purchase_uc', 'user_map_access', ['user_id', 'map_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_map_purchase_uc', 'user_map_access', type_='unique')
    op.add_column('maps', sa.Column('google_embed_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('maps', 'updated_at')
    op.drop_column('maps', 'price')
    op.drop_column('maps', 'region')
    op.drop_index(op.f('ix_stores_map_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
