"""add neighborhood to locations

Revision ID: 06374f38b14b
Revises: f3a7c1e9b2d4
Create Date: 2026-07-22 00:13:05.917323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06374f38b14b'
down_revision: Union[str, Sequence[str], None] = 'f3a7c1e9b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('neighborhood', sa.String(length=255), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'neighborhood')
    # ### end Alembic commands ###
