"""update model

Revision ID: 189662e6c7ac
Revises: 92b388fee6b1
Create Date: 2026-06-17 00:26:06.836631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189662e6c7ac'
down_revision: Union[str, Sequence[str], None] = '92b388fee6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'price_range',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('stores', 'is_featured')
    op.add_column('user_map_access', sa.Column('initial_latitude', sa.Float(), nullable=True))
    op.add_column('user_map_access', sa.Column('initial_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_map_access', 'initial_longitude')
    op.drop_column('user_map_access', 'initial_latitude')
    op.add_column('stores', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('stores', 'price_range',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
