"""clarification on price

Revision ID: 92b388fee6b1
Revises: 020ceb7e35cc
Create Date: 2026-06-16 18:38:47.525114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b388fee6b1'
down_revision: Union[str, Sequence[str], None] = '020ceb7e35cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('map_price', sa.Integer(), nullable=False))
    op.drop_column('maps', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('maps', 'map_price')
    # ### end Alembic commands ###
