"""add session_minted_at to invoices

Revision ID: 9414cdd0d07b
Revises: d798c88d632b
Create Date: 2026-09-29 20:53:19.617943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9414cdd0d07b'
down_revision: Union[str, Sequence[str], None] = 'd798c88d632b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('session_minted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('invoices', 'session_minted_at')
    # ### end Alembic commands ###
