"""move google_place_id from maps to locations

Revision ID: 9caaeef57f5c
Revises: bd1e7cfaa3cd
Create Date: 2026-06-28 00:13:47.911747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9caaeef57f5c'
down_revision: Union[str, Sequence[str], None] = 'bd1e7cfaa3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.drop_column('maps', 'google_place_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('google_place_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('locations', 'google_place_id')
    # ### end Alembic commands ###
