"""add reset_jti to users

Revision ID: a37f9eb6fa1d
Revises: 9414cdd0d07b
Create Date: 2026-09-29 21:07:23.435346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37f9eb6fa1d'
down_revision: Union[str, Sequence[str], None] = '9414cdd0d07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_jti', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('claim_jti', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_jti')
    op.drop_column('users', 'claim_jti')
    # ### end Alembic commands ###
