"""add status column to maps table

Revision ID: e127cc3b5761
Revises: 06374f38b14b
Create Date: 2026-08-07 13:49:55.246405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e127cc3b5761'
down_revision: Union[str, Sequence[str], None] = '06374f38b14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('status', sa.Enum('LIVE', 'WAITLIST', 'DROPPED', name='map_status'), server_default='waitlist', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'status')
    # ### end Alembic commands ###
